# Generated by Django 3.0.5 on 2020-11-20 11:49

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='content_type',
        ),
        migrations.AlterField(
            model_name='blog',
            name='thumbnail',
            field=models.ImageField(default=datetime.datetime(2020, 11, 20, 11, 49, 48, 549799, tzinfo=utc), upload_to='images'),
            preserve_default=False,
        ),
    ]
