# Generated by Django 3.0.5 on 2020-11-21 12:53

from django.db import migrations
import sorl.thumbnail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20201120_1719'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='thumbnail',
            field=sorl.thumbnail.fields.ImageField(upload_to='images'),
        ),
    ]
